---
apiVersion: v1
kind: Service
metadata:
  name: orthocal-client
  namespace: orthocal
  labels:
    app: orthocal-client
    service: nginx
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: orthocal-client
    service: nginx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orthocal-client
  namespace: orthocal
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: orthocal-client
        service: nginx
    spec:
      containers:
      - name: orthocal-client
        imagePullPolicy: Always
        image: brianglass/orthocal-client:latest
        resources:
          requests:
            cpu: 50m
            memory: 10Mi
          limits:
            cpu: 100m
            memory: 15Mi
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
